### ISSUE TITLE
only a question :)

### ISSUE THREAD

**Issue by aleeepp** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#1]
Hi, I am new to this type of bot (I come from freqtrade, which is a great project). This project catches my attention and I want to congratulate you for the effort you put into it!

I ask you a rookie query :)

1> How do you detect that a token has Liquidity?
2> Why are you waiting for some blocks to buy?

Thank you and keep it up!

**Comment by Trading-Tiger** [comment]
Hi aleepp, 
Thanks good luck with the tools!

1 -> txn.py ->line:65 -> self.router.functions.getOutputfromBNBtoToken -> if reverted -> no Liquidity!

2-> some users try to avoid fees from the token, or if the token has liquidity but is disabled for swapping, mainly to gain time before buy!

**Comment by hassansaby23** [comment]
Hey, I just want to tell you that the bot all coins tell It's a honeypot even busd or cake, can you fix it?

Or can you explain to me how this honeypot checker works? and Thanks

**Comment by Trading-Tiger** [comment]
FIXED!
