### ISSUE TITLE
Metamask Error: Internal JSON-RPC error after system interupt by Ctrl+c the program with buy() function

### ISSUE THREAD

**Issue by cuongnguyengit** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#10]
I try bellow:
amount: 0.01
txamount: 5
honeypot: True
takeprofit: 10
awaitBlocks: 50

After the program run too slowly, i used command Ctrl+C. 
I dont know anything happend but now i cant swap in pancakeswap and metamask with the same error:  Internal JSON-RPC.

How to fix the error?

Thank you very much.

**Comment by Trading-Tiger** [comment]
You have used await blocks, it takes about 2.3seconds for one block, 50x2.3 = 115sec Before buy!

Please note that in some countries cryptocurrencies are blocked, so it is not possible to access the RPC in the normal way. Here you may need a VPN or similar.

**Comment by cuongnguyengit** [comment]
Thanks for your response.

The await blocks made my problem following your answer. 
So what difference between await blocks and time.sleep ?

I think that my country's cryptocurrencies are not blocked because i bought by your code (buy()). I only can't run snip().
