### ISSUE TITLE
I dont see the GUI for v1.2 ?

### ISSUE THREAD

**Issue by localpr** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#11]
Hi how do i generate the GUI for v1.2 like you have in the screenshot in the repo ?

thanks!

**Comment by localpr** [comment]
For example this [screenshot](https://camo.githubusercontent.com/9c921f192a01add092ef59f5b101058b8c59e46afd37dfa7b4a01bb860febcae/68747470733a2f2f74726164696e672d7469676572732e636f6d2f6173736574732f696d672f4775692d5072657669657730312e706e67), i dont see slippage or quick buy ?

**Comment by Trading-Tiger** [comment]
The GUI is currently only via Windows executable and the image has not been updated yet.
Quick-Buy/Quick-Sell will be back soon.

Slippage was removed and now calculated by the contract (real LP slippage), token tax is entered in Settings.json.
