### ISSUE TITLE
What's Wrong?

### ISSUE THREAD

**Issue by ZaMoskvorechye** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#12]
I need help getting it started. See [screenshot](https://sun9-74.userapi.com/impg/NOZMfGYGYTfA3m5JmaT1BanJUIFX63javQ6H0g/Q_2lDu_7DcE.jpg?size=473x184&quality=96&sign=ab393bafa71cbed79dd2cdda780c3cad&type=album)

**Comment by Trading-Tiger** [comment]
Hi, Please Try: installing the Visual C++ Redistributable for Visual Studio 2015 run-time components. https://www.microsoft.com/en-us/download/confirmation.aspx?id=48145
