### ISSUE TITLE
A little request

### ISSUE THREAD

**Issue by wangluxu** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#14]
Hello,I am a BSC Bot beginner.I want to know the functions in your contract how to work,but the contract seems to be unauthorized in BSC explorer，so I can't look the your contract code，can you help me？

**Comment by Trading-Tiger** [comment]
Our contract will not be open soure available for security and copying reasons!
But, in the included BSC_Swapper.json, you will find all functions with their arguments, that you can use.
