### ISSUE TITLE
How to compute the total of fee in one transaction?

### ISSUE THREAD

**Issue by cuongnguyengit** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#15]
Many thanks for your project.

I try to explore some documents about transaction fees but I had troubles.
I can't compute the total fee for each transaction.
Can you explain for me? 

Thank you.

**Comment by Trading-Tiger** [comment]
Settings.json : GAS = 6 
But we need GAS_PRICE = 6 * (10**9) = 6000000000 WEI 
Now we have the raw Wei for GAS_PRICE from Gwei.
So ok, now we need to Calculate the Gas for the Data in TX.

Lets say Estimate_Gas retuns 550000:
Estimate Gas = 550000 = GAS_PRICE * Estimate gas = 6000000000 * 550000 = 3300000000000000 

So we maximal pay 3300000000000000 WEI for this Transaction,
3300000000000000 / (10**18) = 0.0033 BNB or with web3 in python: Web3.fromWei(3300000000000000, "ether")

**Comment by cuongnguyengit** [comment]
So with """Attention, they pay 0.7% fees on each transaction.""" .
Where is 0.7%?
How do we know to calculate for it?

**Comment by Trading-Tiger** [comment]
ok, sorry my mistake, I thought you meant the actual miner fees.
Fees... lets rename it to Tax!

Our 0.7% is calculated on your BNB input/output:
(BNBAmount * 7)  / 1000
e.g. 1 * 7 / 1000 = 0.007BNB Fee
