### ISSUE TITLE
Error in fees estimate

### ISSUE THREAD

**Issue by CryptoDoe** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#16]
hey
First of all, amazing job !

Bot was working just fine, then today I start having this error returned

Attention, they pay 0.7% fees on each transaction.
Start Sniper Tool with following arguments:
---------------------------------
Amount for Buy: 0.001 BNB
Token to Interact : 0xdac17f958d2ee523a2206206994597c13d831ec7
Transaction to send: 1
Amount per transaction : 0.00100000
Await Blocks before buy : 0
---------------------------------
Start BuyOnly, buy now with 0.001BNB tokens!
Traceback (most recent call last):
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Sniper.py", line 222, in <module>
    SniperBot().StartUP()
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Sniper.py", line 196, in StartUP
    print(self.TXN.buy_token()[1])
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/txns.py", line 99, in buy_token
    txn.update({ 'gas' : int(self.estimateGas(txn))})
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/txns.py", line 65, in estimateGas
    gas = self.w3.eth.estimateGas({
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/_utils/method_formatters.py", line 580, in raise_solidity_error_on_revert
    raise ContractLogicError('execution reverted')
web3.exceptions.ContractLogicError: execution reverted

It seems some issue with selfEstimate gas

Anyone else having trouble?
Do you have any idea what's wrong ?
I haven't touched any parameter such as gas price or MaxTax

Cheers
A

**Comment by CryptoDoe** [comment]
> hey First of all, amazing job !
> 
> Bot was working just fine, then today I start having this error returned
> 
> ## Attention, they pay 0.7% fees on each transaction.
> Start Sniper Tool with following arguments:
> ## Amount for Buy: 0.001 BNB
> Token to Interact : 0xdac17f958d2ee523a2206206994597c13d831ec7
> Transaction to send: 1
> Amount per transaction : 0.00100000
> Await Blocks before buy : 0
> Start BuyOnly, buy now with 0.001BNB tokens! Traceback (most recent call last): XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Sniper.py", line 222, in SniperBot().StartUP() XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Sniper.py", line 196, in StartUP print(self.TXN.buy_token()[1]) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/txns.py", line 99, in buy_token txn.update({ 'gas' : int(self.estimateGas(txn))}) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/txns.py", line 65, in estimateGas gas = self.w3.eth.estimateGas({ File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/eth.py", line 759, in estimate_gas return self._estimate_gas(transaction, block_identifier) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/module.py", line 57, in caller result = w3.manager.request_blocking(method_str, File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking return self.formatted_response(response, File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 170, in formatted_response apply_error_formatters(error_formatters, response) File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/manager.py", line 70, in apply_error_formatters formatted_resp = pipe(response, error_formatters) File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/web3/_utils/method_formatters.py", line 580, in raise_solidity_error_on_revert raise ContractLogicError('execution reverted') web3.exceptions.ContractLogicError: execution reverted
> 
> It seems some issue with selfEstimate gas
> 
> Anyone else having trouble? Do you have any idea what's wrong ? I haven't touched any parameter such as gas price or MaxTax
> 
> Cheers A

I'

**Comment by CryptoDoe** [comment]
I've tried with USTD to show that the issue is no token address related

**Comment by Alaocitis** [comment]
I got the same issue

**Comment by Trading-Tiger** [comment]
I just looked at the address you tried to trade, this is not a token!
https://bscscan.com/address/0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by CryptoDoe** [comment]
Hey ! Thanks for feedback
My bad. Still, I've tried with several freshly launched token, got the same result

**Comment by Trading-Tiger** [comment]
ok, are you using the Windows executables or the code?
Please give me a token that didn't work so I can reconstruct it.

**Comment by CryptoDoe** [comment]
First experienced with Lord Arena - LORDA
0xc326622fca914ca15fd44dd070232ce3cd358dde

Then tried with several token just launched using dextool scanner, got the same error

Today I tried buyonly and it worked
