### ISSUE TITLE
[Request Feature] - Repeat

### ISSUE THREAD

**Issue by usapanglashing** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#19]
Hello Tigers, would like to request to add a repeat feature for this. Thanks!

**Comment by Trading-Tiger** [comment]
hi,
what exactly do you mean by repeat?
Can you please explain this in more detail.

**Comment by usapanglashing** [comment]
Repeating the same buy and sell action again for the token.. I hope that helps thanks!

**Comment by sam007hero** [comment]
excellent job guys.. but it would be amazing if you add telegram scraper
