### ISSUE TITLE
Wait for liquidity

### ISSUE THREAD

**Issue by Wakeupps** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#2]
Hello, I'm using your project and I find it very helpful!

I have a question: before a new listing the liquidity is disabled. So a possible solution would be checking if the token is a honeypot inside a loop?  Or the wait for block feature already does this? Thanks in advance

**Comment by Trading-Tiger** [comment]
No, WaitBlocks is for Tokens with High fees in the first blocks, e.g. some tokens use 75% Tax in the first 10Blocks after adding Liquidity, with WaitBlocks you can skip this 10 Blocks 👍 

It is generally very dangerous to invest in projects that have the ability to stop trading.
We have something in mind, just don't know exactly when we will implement it.

Greetings!
