### ISSUE TITLE
Why is slippage removed, is it auto calculated?

### ISSUE THREAD

**Issue by timvanuum** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#3]
Hi there,

Awesome bot! Works great!
One question, why is the slippage removed from the script? 
Is it auto calculated?

**Comment by Trading-Tiger** [comment]
Hi timvanuum,

Thanks for the positiv feedback!
Yes, the Smart Contract calculate the best Output amount.

You can set MaxTax in the settings.json.

Greetings!
