### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by anandexclusive** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#32]
I was using it for past 1 month its really good work, I request escape Antibot tokens function and front run function, 

Once again great work tigers,  people like me non technical still bot functions self explanatory, try solving above request, really you were very professional in answering queries too.

**Comment by Trading-Tiger** [comment]
Thank you for your positive feedback, and sorry for the late reply, we will continue to keep our tools up to date.
