### ISSUE TITLE
web3.exceptions.ContractLogicError: execution reverted: TransferHelper: TRANSFER_FROM_FAILED

### ISSUE THREAD

**Issue by jemkein** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#33]
I get this Error when I try to sell on some coins.
I read that this could be because of slippage.
But i tried several Settings for MaxSellTax but none worked.
How can I fix this? :)

**Comment by Trading-Tiger** [comment]
Fixed in v2.0!
