### ISSUE TITLE
Code for honeypot checker?

### ISSUE THREAD

**Issue by Raveboi334** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#34]
Hi there, I love your bot, I'm a crypto security researcher and I'm really interested in your honeypot checker smart contract:

https://bscscan.com/address/0x1Ba0c582354c628Ab621b1bd0328528Fbb8d80fC#code

However the code hasn't been verified. Would it be possible for you to share the code or how I would be able to get the code?

Thank you so much.

**Comment by Trading-Tiger** [comment]
come on people, this will then be copied and used further, you can use it freely, in the ABI are all the necessary information to perform a Web3 Call!

**Comment by Raveboi334** [comment]
I know, but it would be amazing if I could see the solidity code for it or you could verify the contract on bscscan, would help me so much. Thank you 🙏
