### ISSUE TITLE
Settings.json

### ISSUE THREAD

**Issue by MaksRe** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#36]
Hello. Tell me please
what are the rules for configuring these parameters?

"RPC": "https://bsc-dataseed1.defibit.io/",
"GAS": 6,
"MaxSellTax": 15,
"MaxBuyTax": 15

in the Settings.json

**Comment by Trading-Tiger** [comment]
This is the Json format, you can learn more here. https://www.w3schools.com/js/js_json_intro.asp

RPC is websocket or https from your provider.
Sell/BuyTax comes from the tokenInformation if your settings about this no buy are execute.
everything is up to you.
