### ISSUE TITLE
"Sell all tokens" is malfunctioning and lost my BNB

### ISSUE THREAD

**Issue by syphlect** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#37]
Hi! Great job on the bot so please don't take this the wrong way but i tried selling all of my tokens i previously purchased. I tried the bot buy feature and it works fine, but the "Sell all tokens" lost my BNB.

I purchased this token during a pre-sale 0xef9e0b75e78c3398329595b8d33b0636b0055455 - I wanted to use your bot to sell all tokens fast and all at once so i pressed the button and it said Successful but then i noticed that the BNB disappeared from my wallet.

Here's the tx for the transaction that was made when i wanted to sell all tokens - https://bscscan.com/tx/0xf8d956b6f38ec7353ce9e38ec122fdfac61989202759a90659f02727f2274009
My BSC address that was used for the bot - 0x54D0fa1FD92155E858d42376bD07B52f0272dfCa

You can see I didn't transfer those BNBs anywhere, but they're gone from my account.

Can you help me?

**Comment by Trading-Tiger** [comment]
Hi syphlect,
I just had a look at your transaction.
As I see in it you have sold your tokens for around 25$ (0.05) BNB, these were then also transferred to your address.


![Screenshot](https://user-images.githubusercontent.com/79805603/147742038-e31800aa-1037-48f8-bc91-c6ca1746050b.png)

According to the transaction, they have received BNB!

**Comment by syphlect** [comment]
Ah damn it, that means my wallet has been compromised :(

Alright you can remove this so people don't think it's your fault (it isn't)

**Comment by syphlect** [comment]
However, i didn't make those transfers. The BNB is being transferred to an
address I don't know
https://bscscan.com/address/0x37050713bf53bc8a4f536ae962d4ef0a51bf30f6

You can see the address beginning with 0x37 has compromised my wallet. Oh
well, I'll format my PC.
