### ISSUE TITLE
Router for Transactions

### ISSUE THREAD

**Issue by Wakeupps** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#4]
Hello,

I was reading the code in order to understand  and I noticed that there is a wallet (ROUTER) that is doing all the transactions for us: 0xde937d83e62764c1f4809b87d4c8c5779c351fbf

Is that what you mean by "You pay 1% fees on each transaction." ? And how can I use this project in testnet? I know how to configurate, but which router provider should I use in this case?

Thanks in advance

**Comment by Trading-Tiger** [comment]
Hi Wakeupps,

We have created our own "proxy" router.
They pay 1% fees on the amount they swap (simple solution as no one buys TIGS).

Used in Testnet:
"BUSD":"0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee",
"Pancakeswap Router": "0xD99D1c33F9fC3444f8101754aBC46c52416550D1",
"TIGSPROXYROUTER": "0x92E8c3E4f7854FAADD7281E7196cc48e147Ec629"

 https://testnet.bscscan.com/address/0x92E8c3E4f7854FAADD7281E7196cc48e147Ec629
