### ISSUE TITLE
Error when selling

### ISSUE THREAD

**Issue by xDevilz** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#41]
Token: 0x156df0dd6300c73ac692d805720967cf4464776e
web3.exceptions.ContractLogicError: execution reverted: TransferHelper: TRANSFER_FROM_FAILED

When I set max gas to 1.000.000 and remove line txn.update({ 'gas' : int(self.estimateGas(txn))}), it generated tx, but still failed:
https://bscscan.com/tx/0xb880fe3a267069c793be48155c9d4cfcdcc063f963793d0b53142c9bf075e378

I tried increasing selltax, slippage, but not ok
Manually swap on pancakeswap is good.

**Comment by dedezinholindo** [comment]
i need help too

**Comment by Trading-Tiger** [comment]
Thanks for the message and the TX hash!
With this we could work well!
We have updated the code today, also this kind of token works now.

**Comment by daniallotfi** [comment]
Hello sir how are you ?
This is My Problem , 
How Can Please Help Me ? :(
https://bscscan.com/tx/0xceb2647646ef7bb0bbb5adbca632ae1620c7134bd9a8626c1ae59bfac2423ada
