### ISSUE TITLE
The system cannot find message text for message number 0x2350 in the message file for Application. 

### ISSUE THREAD

**Issue by anandexclusive** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#45]
please clarify on this message on the top of the cmd

**Comment by erra-tech** [comment]
Same for me, exclude the folder in windows defender Helps!

**Comment by Trading-Tiger** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/window-errorthe-system-cannot-find-message-text/2556e467-9f0a-4a8f-a58e-a7485e00ebcb
