### ISSUE TITLE
execution reverted: PancakeLibrary: INSUFFICIENT_INPUT_AMOUNT

### ISSUE THREAD

**Issue by dnKaratzas** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#49]
Hello I have issue with check honeypot.
I added a print(e) at line 192 and the result is :
await Dev Enables Swapping execution reverted: PancakeLibrary: INSUFFICIENT_INPUT_AMOUNT

**Comment by Trading-Tiger** [comment]
This is completely normal if there is no liquidity in the token.
The bot will check until they stop or liquidity is found.
