### ISSUE TITLE
Self hosting the HoneyPot checker

### ISSUE THREAD

**Issue by timvanuum** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#5]
Hello,

Another question, I'm getting a timeout on the honeypot checker.
I see you are hosting that honeypot checker yourself.

For reliabilty is it possible we can host that honeypot checker ourselves?

**Comment by AdamSabhi** [comment]
Yes, me too

**Comment by BrokedTV** [comment]
Yeah, i would love to be able to self host the checker for higher reliability which is now lacking, a step forward would also be to move the checker locally!
Those things would be awesome, thanks!

**Comment by Trading-Tiger** [comment]
We need some time, this function will be integrated in the next Smart Contract version.
