### ISSUE TITLE
Token lost to your contract

### ISSUE THREAD

**Issue by hhhwrld** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#55]
Hi, I run your program, but only sent my token to your contract address and no later liquidity transaction reward, can you confirm? I need my token back

<img width="909" alt="image" src="https://user-images.githubusercontent.com/105514268/168338937-7bd8c1b9-0dd6-4d00-b32c-429548f7ec74.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/105514268/168339367-a23d4740-912f-4900-8fb6-799f00e3ddf3.png">

**Comment by Tovi-A** [comment]
> Hi, I run your program, but only sent my token to your contract address and no later liquidity transaction reward, can you confirm? I need my token back
> 
> <img alt="image" width="909" src="https://user-images.githubusercontent.com/105514268/168338937-7bd8c1b9-0dd6-4d00-b32c-429548f7ec74.png">
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/105514268/168339367-a23d4740-912f-4900-8fb6-799f00e3ddf3.png">

Did you succeed ？？

**Comment by hhhwrld** [comment]
> 

Definitely not!

**Comment by Trading-Tiger** [comment]
Hi @hhhwrld & @Tovi-A, thank you for your interest and feedback to Trading-Tigers Sniper bot!

Next time please copy the terminal output directly, then I don't have to bother to copy it ;)

What strikes me directly is their low volume, do not forget that they pay transaction fees.
Here red marked!
![tx-01-hhhwrld](https://user-images.githubusercontent.com/79805603/168470516-29969915-98fb-4d2c-9d5d-a6a903c6f1b8.png)

Then you let the bot sell and you paid more transaction fees for these transactions than you traded!
https://bscscan.com/tx/0x4f168866e23646beefa06328f4903921214dc3a05e64ffaa01bf118c08d11084


I hope I could help you,
Many greetings

Seven
