### ISSUE TITLE
This contract is not verified and it should be.

### ISSUE THREAD

**Issue by iv7dev** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#57]
This contract is not verified and it should be. everyone should know what it does.
 ** swapper_address = Web3.toChecksumAddress("0x18be7f977Ec1217B71D0C134FBCFF36Ea4366fCD")

**Comment by chenrenjing** [comment]
> This contract is not verified and it should be. everyone should know what it does. ** swapper_address = Web3.toChecksumAddress("0x18be7f977Ec1217B71D0C134FBCFF36Ea4366fCD")

hello,do you know this contract  what it does?

**Comment by cchris-org** [comment]
Unknown and unverified contract, which is used in this code for swap tokens, can easily drain your wallet to zero. Stay far away from it. Serious contracts are open to everyone.

**Comment by Trading-Tiger** [comment]
The Smart Contract was just not verified to protect us from Copy past.
https://bscscan.com/tx/0x9c3154707a6b4b98719ece035bd75becb551299b84c776888989411111315dcc

We do not scam, we just take a small fee! ;)
