### ISSUE TITLE
A quick question around Honeypot Checker...

### ISSUE THREAD

**Issue by furritos** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#58]
Hi, great app but I do have a quick question.

In the honeypot check section, the call to the `getTokenInformations` contract returns an array.  The values in index 5 and 6 are boolean and if they are both `True` then it's a honeypot.

My question: what is index 5 checking for?
Also, what is index 6 checking for?

I don't really want to know the code, all I want to know what is it checking in those indexes.

Thanks!

**Comment by furritos** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/2133717/205411765-5f1bc322-d118-4edc-8f70-1fde705b77af.png">

**Comment by Trading-Tiger** [comment]
Hi @furritos ,
Index 4 checks whether the purchase was successful.
Index 5 checks if it was possible to approve the purchased token.
Index 6 checks if the sale was successful.

In the new version, there is now an Index 7.
Index 7: Whether the expected amount of tokens reached the contract, essentially a check to see if BNB was received after the sale with 20% slippage.
