### ISSUE TITLE
i got fail

### ISSUE THREAD

**Issue by MakliJ** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#6]
Waiting BlocksHTTPSConnectionPool(host='ishoneypot.trading-tigers.com', port=443): Max retries exceeded with url: /token/0x265f638eab14dd43d80bb71aae3289b1c6d46a3f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BC46A90430>: Failed to establish a new connection: [WinError 10060]

what does it mean bro and how to resolve this problem?

**Comment by Trading-Tiger** [comment]
This was probably temporarily unavailable due to maintenance work.
