### ISSUE TITLE
'fromETHtoToken' object has no attribute 'buildTransaction'

### ISSUE THREAD

**Issue by myiisvif** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#62]
txn = self.swapper.functions.fromETHtoToken(
                    minAmount,
                    TokenWay,
                    DexWay,
                    self.address
                ).buildTransaction(
                    {'from': self.address,
                     'gasPrice': self.gas_price,
                     'nonce': self.w3.eth.get_transaction_count(self.address),
                     'value': int(self.quantity * (10**18))}
                )

Error：
'fromETHtoToken' object has no attribute 'buildTransaction'

**Comment by Trading-Tiger** [comment]
hi,
the requirements.txt has been updated, please use Web3.py v5.31.0
