### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by SAQOPAT** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#64]
DO I HAVE TO PAY ANY FEE?

**Comment by Leandrost15** [comment]
Hello, could you please clarify if there are any fees associated with this? It would be helpful to have a clearer understanding of any potential costs involved

**Comment by Trading-Tiger** [comment]
Hello, 
here are some information about the Fee we take.

https://docs.trading-tigers.com/tokenomics/trading-fees
