### ISSUE TITLE
[request] add front-running feature to sell before rug-pull

### ISSUE THREAD

**Issue by gabrieleginestroni** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#7]
Hello, 
it would be nice to implement an enhanced check when the script has completed the buy transaction and it's waiting for the take profit. The bot should scan all the pending transaction and, if a removeLiquidity | changeFees method is being called, the bot should immediately front-run that transaction by sending a sell order with higher gwei.
Thanks for your effort

**Comment by dederico99** [comment]
That would be an absolutely amazing feature to implement the bot!

**Comment by zPave** [comment]
It would be very nice

**Comment by Trading-Tiger** [comment]
We have already done some tests, and are trying to integrate this in a timely manner.

- We like the idea very much, and can be very useful!

**Comment by localpr** [comment]
Hey Tigers, yes I upvote this suggestion. Thank you very much!

**Comment by ariffinhamzah** [comment]
Hope this function still on track and finally released..

**Comment by lamxoan92** [comment]
can I snip by BUSD????

**Comment by bcheeves** [comment]
Yes, would love to have this feature, lots of rugpulls on BSC

**Comment by thefallentoaster** [comment]
Please proceed to our discord so we can discuss this: https://discord.gg/cwQheEDb

**Comment by Trading-Tiger** [comment]
Regrettably, it must be emphasized that front-running bigger transactions is unfeasible. These transactions get incorporated into the blockchain considerably quicker than swap transactions, making it impossible to outpace the manipulative transactions executed by the token developer.

Moreover, the token developer employs gas prices of 99 GWEI or even higher, an exorbitant cost for swap transactions.

Exercise caution and prioritize safety – refrain from purchasing Telegram Chill tokens.
