### ISSUE TITLE
add quick sell

### ISSUE THREAD

**Issue by MakliJ** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#9]
Hello again, would be nice to see the next feature:
For example, if bot bought the token from start and u chosed to sell with 400% profit, but its cant be true and no time for sell via pancake because presalers can sell it faster, just add the function with fast sell ignoring the 400% setted before profit.
F/E: 
--Do u want sell now? (Y/N)
--Y
--Selling
--TX ID:

**Comment by Trading-Tiger** [comment]
After Next update this is available!
